twist_mux:
  ros__parameters:
    use_stamped: true

    # Higher Priority -> Takes control over lower priority
    topics:
      nav2:
        topic: cmd_vel_nav_out
        timeout: 0.5
        priority: 70
      keyboard:
        topic: cmd_vel_keyboard
        timeout: 0.5
        priority: 90
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 100

    locks:
      # Block all output on estop
      # This is a SOFTWARE LEVEL estop. The motors will still have power and are still capable of driving.
      estop:
        topic: estop
        timeout: 0.0
        priority: 255

