# TODO document everything being done here

services:
  ora_zed:
    image: dmocnik/ora_zed:latest
    container_name: ora_zed
    runtime: nvidia
    network_mode: host
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
      NVIDIA_DRIVER_CAPABILITIES: all
      
    labels:
      - autoheal=true

    volumes:
      - /tmp:/tmp
      - /dev:/dev
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/

      #ZED ROS2 Params
      - ./config/zed_params.yaml:/config/zed_params.yaml:ro

    command: >
      bash -lc
        ". install/local_setup.bash &&
        ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2i ros_params_override_path:=/config/zed_params.yaml"

    healthcheck: #Monitor the container based on whether or not the ZED is physically connected
      test:
        [
          "CMD-SHELL",
          "grep -Riq 'stereolabs' /sys/bus/usb/devices/*/manufacturer /sys/bus/usb/devices/*/product"
        ]
      interval: 10s
      timeout: 5s
      retries: 1
      start_period: 30s

    restart: unless-stopped
    
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
